/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnode.nix;

public final class DimensionType {
  public final static DimensionType Sample = new DimensionType("Sample");
  public final static DimensionType Set = new DimensionType("Set");
  public final static DimensionType Range = new DimensionType("Range");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DimensionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DimensionType.class + " with value " + swigValue);
  }

  private DimensionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DimensionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DimensionType(String swigName, DimensionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DimensionType[] swigValues = { Sample, Set, Range };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

