/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnode.nix;

public class FeatureVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FeatureVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FeatureVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_FeatureVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FeatureVector() {
    this(nixJNI.new_FeatureVector__SWIG_0(), true);
  }

  public FeatureVector(long n) {
    this(nixJNI.new_FeatureVector__SWIG_1(n), true);
  }

  public long size() {
    return nixJNI.FeatureVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nixJNI.FeatureVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nixJNI.FeatureVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nixJNI.FeatureVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nixJNI.FeatureVector_clear(swigCPtr, this);
  }

  public void add(Feature x) {
    nixJNI.FeatureVector_add(swigCPtr, this, Feature.getCPtr(x), x);
  }

  public Feature get(int i) {
    return new Feature(nixJNI.FeatureVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Feature val) {
    nixJNI.FeatureVector_set(swigCPtr, this, i, Feature.getCPtr(val), val);
  }

}
