/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnode.nix;

public final class FileMode {
  public final static FileMode ReadOnly = new FileMode("ReadOnly", nixJNI.FileMode_ReadOnly_get());
  public final static FileMode ReadWrite = new FileMode("ReadWrite");
  public final static FileMode Overwrite = new FileMode("Overwrite");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FileMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FileMode.class + " with value " + swigValue);
  }

  private FileMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FileMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FileMode(String swigName, FileMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FileMode[] swigValues = { ReadOnly, ReadWrite, Overwrite };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

