/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnode.nix;

public class MultiTagVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MultiTagVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiTagVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_MultiTagVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MultiTagVector() {
    this(nixJNI.new_MultiTagVector__SWIG_0(), true);
  }

  public MultiTagVector(long n) {
    this(nixJNI.new_MultiTagVector__SWIG_1(n), true);
  }

  public long size() {
    return nixJNI.MultiTagVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nixJNI.MultiTagVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nixJNI.MultiTagVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nixJNI.MultiTagVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nixJNI.MultiTagVector_clear(swigCPtr, this);
  }

  public void add(MultiTag x) {
    nixJNI.MultiTagVector_add(swigCPtr, this, MultiTag.getCPtr(x), x);
  }

  public MultiTag get(int i) {
    return new MultiTag(nixJNI.MultiTagVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, MultiTag val) {
    nixJNI.MultiTagVector_set(swigCPtr, this, i, MultiTag.getCPtr(val), val);
  }

}
