/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnode.nix;

public class MultiTag {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MultiTag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiTag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_MultiTag(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MultiTag() {
    this(nixJNI.new_MultiTag__SWIG_0(), true);
  }

  public MultiTag(MultiTag other) {
    this(nixJNI.new_MultiTag__SWIG_1(MultiTag.getCPtr(other), other), true);
  }

  public DataArray positions() {
    return new DataArray(nixJNI.MultiTag_positions__SWIG_0(swigCPtr, this), true);
  }

  public void positions(String name_or_id) {
    nixJNI.MultiTag_positions__SWIG_1(swigCPtr, this, name_or_id);
  }

  public void positions(DataArray positions) {
    nixJNI.MultiTag_positions__SWIG_2(swigCPtr, this, DataArray.getCPtr(positions), positions);
  }

  public boolean hasPositions() {
    return nixJNI.MultiTag_hasPositions(swigCPtr, this);
  }

  public DataArray extents() {
    return new DataArray(nixJNI.MultiTag_extents__SWIG_0(swigCPtr, this), true);
  }

  public void extents(DataArray extents) {
    nixJNI.MultiTag_extents__SWIG_1(swigCPtr, this, DataArray.getCPtr(extents), extents);
  }

  public void extents(String name_or_id) {
    nixJNI.MultiTag_extents__SWIG_2(swigCPtr, this, name_or_id);
  }

  public void removeExtents() {
    nixJNI.MultiTag_removeExtents(swigCPtr, this);
  }

  public StringVector units() {
    return new StringVector(nixJNI.MultiTag_units__SWIG_0(swigCPtr, this), true);
  }

  public void units(StringVector units) {
    nixJNI.MultiTag_units__SWIG_1(swigCPtr, this, StringVector.getCPtr(units), units);
  }

  public void removeUnits() {
    nixJNI.MultiTag_removeUnits(swigCPtr, this);
  }

  public boolean hasReference(DataArray reference) {
    return nixJNI.MultiTag_hasReference__SWIG_0(swigCPtr, this, DataArray.getCPtr(reference), reference);
  }

  public boolean hasReference(String name_or_id) {
    return nixJNI.MultiTag_hasReference__SWIG_1(swigCPtr, this, name_or_id);
  }

  public long referenceCount() {
    return nixJNI.MultiTag_referenceCount(swigCPtr, this);
  }

  public DataArray getReference(String name_or_id) {
    return new DataArray(nixJNI.MultiTag_getReference__SWIG_0(swigCPtr, this, name_or_id), true);
  }

  public DataArray getReference(long index) {
    return new DataArray(nixJNI.MultiTag_getReference__SWIG_1(swigCPtr, this, index), true);
  }

  public void addReference(String name_or_id) {
    nixJNI.MultiTag_addReference__SWIG_0(swigCPtr, this, name_or_id);
  }

  public void addReference(DataArray reference) {
    nixJNI.MultiTag_addReference__SWIG_1(swigCPtr, this, DataArray.getCPtr(reference), reference);
  }

  public boolean removeReference(String name_or_id) {
    return nixJNI.MultiTag_removeReference__SWIG_0(swigCPtr, this, name_or_id);
  }

  public boolean removeReference(DataArray reference) {
    return nixJNI.MultiTag_removeReference__SWIG_1(swigCPtr, this, DataArray.getCPtr(reference), reference);
  }

  public DataArrayVector references(SWIGTYPE_p_util__FilterT_nix__DataArray_t__type filter) {
    return new DataArrayVector(nixJNI.MultiTag_references__SWIG_0(swigCPtr, this, SWIGTYPE_p_util__FilterT_nix__DataArray_t__type.getCPtr(filter)), true);
  }

  public DataArrayVector references() {
    return new DataArrayVector(nixJNI.MultiTag_references__SWIG_1(swigCPtr, this), true);
  }

  public void references(DataArrayVector references) {
    nixJNI.MultiTag_references__SWIG_2(swigCPtr, this, DataArrayVector.getCPtr(references), references);
  }

  public boolean hasFeature(String name_or_id) {
    return nixJNI.MultiTag_hasFeature__SWIG_0(swigCPtr, this, name_or_id);
  }

  public boolean hasFeature(Feature feature) {
    return nixJNI.MultiTag_hasFeature__SWIG_1(swigCPtr, this, Feature.getCPtr(feature), feature);
  }

  public long featureCount() {
    return nixJNI.MultiTag_featureCount(swigCPtr, this);
  }

  public Feature getFeature(String name_or_id) {
    return new Feature(nixJNI.MultiTag_getFeature__SWIG_0(swigCPtr, this, name_or_id), true);
  }

  public Feature getFeature(long index) {
    return new Feature(nixJNI.MultiTag_getFeature__SWIG_1(swigCPtr, this, index), true);
  }

  public FeatureVector features(SWIGTYPE_p_util__FilterT_nix__Feature_t__type filter) {
    return new FeatureVector(nixJNI.MultiTag_features__SWIG_0(swigCPtr, this, SWIGTYPE_p_util__FilterT_nix__Feature_t__type.getCPtr(filter)), true);
  }

  public FeatureVector features() {
    return new FeatureVector(nixJNI.MultiTag_features__SWIG_1(swigCPtr, this), true);
  }

  public Feature createFeature(DataArray data, LinkType link_type) {
    return new Feature(nixJNI.MultiTag_createFeature__SWIG_0(swigCPtr, this, DataArray.getCPtr(data), data, link_type.swigValue()), true);
  }

  public Feature createFeature(String name_or_id, LinkType link_type) {
    return new Feature(nixJNI.MultiTag_createFeature__SWIG_1(swigCPtr, this, name_or_id, link_type.swigValue()), true);
  }

  public boolean deleteFeature(String name_or_id) {
    return nixJNI.MultiTag_deleteFeature__SWIG_0(swigCPtr, this, name_or_id);
  }

  public boolean deleteFeature(Feature feature) {
    return nixJNI.MultiTag_deleteFeature__SWIG_1(swigCPtr, this, Feature.getCPtr(feature), feature);
  }

}
