/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnode.nix;

public class OptionalDouble {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OptionalDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionalDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_OptionalDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptionalDouble(double arg0) {
    this(nixJNI.new_OptionalDouble(arg0), true);
  }

  public double get() {
    return nixJNI.OptionalDouble_get(swigCPtr, this);
  }

  public boolean isPresent() {
    return nixJNI.OptionalDouble_isPresent(swigCPtr, this);
  }

}
