/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnode.nix;

public class Property {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Property(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Property obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_Property(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Property() {
    this(nixJNI.new_Property__SWIG_0(), true);
  }

  public Property(Property other) {
    this(nixJNI.new_Property__SWIG_1(Property.getCPtr(other), other), true);
  }

  public String name() {
    return nixJNI.Property_name(swigCPtr, this);
  }

  public void definition(String definition) {
    nixJNI.Property_definition__SWIG_0(swigCPtr, this, definition);
  }

  public OptionalString definition() {
    return new OptionalString(nixJNI.Property_definition__SWIG_1(swigCPtr, this), true);
  }

  public void removeDefinition() {
    nixJNI.Property_removeDefinition(swigCPtr, this);
  }

  public void mapping(String mapping) {
    nixJNI.Property_mapping__SWIG_0(swigCPtr, this, mapping);
  }

  public OptionalString mapping() {
    return new OptionalString(nixJNI.Property_mapping__SWIG_1(swigCPtr, this), true);
  }

  public void removeMapping() {
    nixJNI.Property_removeMapping(swigCPtr, this);
  }

  public DataType dataType() {
    return DataType.swigToEnum(nixJNI.Property_dataType(swigCPtr, this));
  }

  public void unit(String unit) {
    nixJNI.Property_unit__SWIG_0(swigCPtr, this, unit);
  }

  public OptionalString unit() {
    return new OptionalString(nixJNI.Property_unit__SWIG_1(swigCPtr, this), true);
  }

  public void removeUnit() {
    nixJNI.Property_removeUnit(swigCPtr, this);
  }

  public void deleteValues() {
    nixJNI.Property_deleteValues(swigCPtr, this);
  }

  public long valueCount() {
    return nixJNI.Property_valueCount(swigCPtr, this);
  }

  public void values(ValueVector values) {
    nixJNI.Property_values__SWIG_0(swigCPtr, this, ValueVector.getCPtr(values), values);
  }

  public ValueVector values() {
    return new ValueVector(nixJNI.Property_values__SWIG_1(swigCPtr, this), true);
  }

  public void removeValues() {
    nixJNI.Property_removeValues(swigCPtr, this);
  }

  public int compare(Property other) {
    return nixJNI.Property_compare(swigCPtr, this, Property.getCPtr(other), other);
  }

}
