/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class BlockVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BlockVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BlockVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_BlockVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BlockVector() {
    this(nixJNI.new_BlockVector__SWIG_0(), true);
  }

  public BlockVector(long n) {
    this(nixJNI.new_BlockVector__SWIG_1(n), true);
  }

  public long size() {
    return nixJNI.BlockVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nixJNI.BlockVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nixJNI.BlockVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nixJNI.BlockVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nixJNI.BlockVector_clear(swigCPtr, this);
  }

  public void add(Block x) {
    nixJNI.BlockVector_add(swigCPtr, this, Block.getCPtr(x), x);
  }

  public Block get(int i) {
    return new Block(nixJNI.BlockVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Block val) {
    nixJNI.BlockVector_set(swigCPtr, this, i, Block.getCPtr(val), val);
  }

}
