/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class DataType {
  public final static DataType Bool = new DataType("Bool");
  public final static DataType Char = new DataType("Char");
  public final static DataType Float = new DataType("Float");
  public final static DataType Double = new DataType("Double");
  public final static DataType Int8 = new DataType("Int8");
  public final static DataType Int16 = new DataType("Int16");
  public final static DataType Int32 = new DataType("Int32");
  public final static DataType Int64 = new DataType("Int64");
  public final static DataType UInt8 = new DataType("UInt8");
  public final static DataType UInt16 = new DataType("UInt16");
  public final static DataType UInt32 = new DataType("UInt32");
  public final static DataType UInt64 = new DataType("UInt64");
  public final static DataType String = new DataType("String");
  public final static DataType Date = new DataType("Date");
  public final static DataType DateTime = new DataType("DateTime");
  public final static DataType Opaque = new DataType("Opaque");
  public final static DataType Nothing = new DataType("Nothing", nixJNI.DataType_Nothing_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DataType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DataType.class + " with value " + swigValue);
  }

  private DataType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DataType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DataType(String swigName, DataType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DataType[] swigValues = { Bool, Char, Float, Double, Int8, Int16, Int32, Int64, UInt8, UInt16, UInt32, UInt64, String, Date, DateTime, Opaque, Nothing };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

