/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DataArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_DataArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataArray() {
    this(nixJNI.new_DataArray__SWIG_0(), true);
  }

  public DataArray(DataArray other) {
    this(nixJNI.new_DataArray__SWIG_1(DataArray.getCPtr(other), other), true);
  }

  public SWIGTYPE_p_boost__optionalT_std__string_t label() {
    return new SWIGTYPE_p_boost__optionalT_std__string_t(nixJNI.DataArray_label__SWIG_0(swigCPtr, this), true);
  }

  public void label(String label) {
    nixJNI.DataArray_label__SWIG_1(swigCPtr, this, label);
  }

  public void removeLabel() {
    nixJNI.DataArray_removeLabel(swigCPtr, this);
  }

  public SWIGTYPE_p_boost__optionalT_std__string_t unit() {
    return new SWIGTYPE_p_boost__optionalT_std__string_t(nixJNI.DataArray_unit__SWIG_0(swigCPtr, this), true);
  }

  public void removeUnit() {
    nixJNI.DataArray_removeUnit(swigCPtr, this);
  }

  public void unit(String unit) {
    nixJNI.DataArray_unit__SWIG_1(swigCPtr, this, unit);
  }

  public SWIGTYPE_p_boost__optionalT_double_t expansionOrigin() {
    return new SWIGTYPE_p_boost__optionalT_double_t(nixJNI.DataArray_expansionOrigin__SWIG_0(swigCPtr, this), true);
  }

  public void expansionOrigin(double expansion_origin) {
    nixJNI.DataArray_expansionOrigin__SWIG_1(swigCPtr, this, expansion_origin);
  }

  public void removeExpansionOrigin() {
    nixJNI.DataArray_removeExpansionOrigin(swigCPtr, this);
  }

  public void polynomCoefficients(DoubleVector polynom_coefficients) {
    nixJNI.DataArray_polynomCoefficients__SWIG_0(swigCPtr, this, DoubleVector.getCPtr(polynom_coefficients), polynom_coefficients);
  }

  public DoubleVector polynomCoefficients() {
    return new DoubleVector(nixJNI.DataArray_polynomCoefficients__SWIG_1(swigCPtr, this), true);
  }

  public void removePolynomCoefficients() {
    nixJNI.DataArray_removePolynomCoefficients(swigCPtr, this);
  }

  public DimensionVector dimensions(SWIGTYPE_p_util__FilterT_nix__Dimension_t__type filter) {
    return new DimensionVector(nixJNI.DataArray_dimensions__SWIG_0(swigCPtr, this, SWIGTYPE_p_util__FilterT_nix__Dimension_t__type.getCPtr(filter)), true);
  }

  public DimensionVector dimensions() {
    return new DimensionVector(nixJNI.DataArray_dimensions__SWIG_1(swigCPtr, this), true);
  }

  public long dimensionCount() {
    return nixJNI.DataArray_dimensionCount(swigCPtr, this);
  }

  public Dimension getDimension(long id) {
    return new Dimension(nixJNI.DataArray_getDimension(swigCPtr, this, id), true);
  }

  public SetDimension appendSetDimension() {
    return new SetDimension(nixJNI.DataArray_appendSetDimension(swigCPtr, this), true);
  }

  public RangeDimension appendRangeDimension(DoubleVector ticks) {
    return new RangeDimension(nixJNI.DataArray_appendRangeDimension(swigCPtr, this, DoubleVector.getCPtr(ticks), ticks), true);
  }

  public SampledDimension appendSampledDimension(double sampling_interval) {
    return new SampledDimension(nixJNI.DataArray_appendSampledDimension(swigCPtr, this, sampling_interval), true);
  }

  public SetDimension createSetDimension(long id) {
    return new SetDimension(nixJNI.DataArray_createSetDimension(swigCPtr, this, id), true);
  }

  public RangeDimension createRangeDimension(long id, DoubleVector ticks) {
    return new RangeDimension(nixJNI.DataArray_createRangeDimension(swigCPtr, this, id, DoubleVector.getCPtr(ticks), ticks), true);
  }

  public SampledDimension createSampledDimension(long id, double sampling_interval) {
    return new SampledDimension(nixJNI.DataArray_createSampledDimension(swigCPtr, this, id, sampling_interval), true);
  }

  public boolean deleteDimension(long id) {
    return nixJNI.DataArray_deleteDimension(swigCPtr, this, id);
  }

  public void getDataDirect(DataType dtype, SWIGTYPE_p_void data, SWIGTYPE_p_NDSize count, SWIGTYPE_p_NDSize offset) {
    nixJNI.DataArray_getDataDirect(swigCPtr, this, dtype.swigValue(), SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_NDSize.getCPtr(count), SWIGTYPE_p_NDSize.getCPtr(offset));
  }

  public void setDataDirect(DataType dtype, SWIGTYPE_p_void data, SWIGTYPE_p_NDSize count, SWIGTYPE_p_NDSize offset) {
    nixJNI.DataArray_setDataDirect(swigCPtr, this, dtype.swigValue(), SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_NDSize.getCPtr(count), SWIGTYPE_p_NDSize.getCPtr(offset));
  }

  public SWIGTYPE_p_NDSize dataExtent() {
    return new SWIGTYPE_p_NDSize(nixJNI.DataArray_dataExtent__SWIG_0(swigCPtr, this), true);
  }

  public void dataExtent(SWIGTYPE_p_NDSize extent) {
    nixJNI.DataArray_dataExtent__SWIG_1(swigCPtr, this, SWIGTYPE_p_NDSize.getCPtr(extent));
  }

  public DataType dataType() {
    return DataType.swigToEnum(nixJNI.DataArray_dataType(swigCPtr, this));
  }

  public void appendData(DataType dtype, SWIGTYPE_p_void data, SWIGTYPE_p_NDSize count, long axis) {
    nixJNI.DataArray_appendData(swigCPtr, this, dtype.swigValue(), SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_NDSize.getCPtr(count), axis);
  }

}
