/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DataArrayVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataArrayVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataArrayVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_DataArrayVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataArrayVector() {
    this(nixJNI.new_DataArrayVector__SWIG_0(), true);
  }

  public DataArrayVector(long n) {
    this(nixJNI.new_DataArrayVector__SWIG_1(n), true);
  }

  public long size() {
    return nixJNI.DataArrayVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nixJNI.DataArrayVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nixJNI.DataArrayVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nixJNI.DataArrayVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nixJNI.DataArrayVector_clear(swigCPtr, this);
  }

  public void add(DataArray x) {
    nixJNI.DataArrayVector_add(swigCPtr, this, DataArray.getCPtr(x), x);
  }

  public DataArray get(int i) {
    return new DataArray(nixJNI.DataArrayVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, DataArray val) {
    nixJNI.DataArrayVector_set(swigCPtr, this, i, DataArray.getCPtr(val), val);
  }

}
