/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DimensionVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DimensionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DimensionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_DimensionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DimensionVector() {
    this(nixJNI.new_DimensionVector__SWIG_0(), true);
  }

  public DimensionVector(long n) {
    this(nixJNI.new_DimensionVector__SWIG_1(n), true);
  }

  public long size() {
    return nixJNI.DimensionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nixJNI.DimensionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nixJNI.DimensionVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nixJNI.DimensionVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nixJNI.DimensionVector_clear(swigCPtr, this);
  }

  public void add(Dimension x) {
    nixJNI.DimensionVector_add(swigCPtr, this, Dimension.getCPtr(x), x);
  }

  public Dimension get(int i) {
    return new Dimension(nixJNI.DimensionVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Dimension val) {
    nixJNI.DimensionVector_set(swigCPtr, this, i, Dimension.getCPtr(val), val);
  }

}
