/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Dimension {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Dimension(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Dimension obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_Dimension(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Dimension() {
    this(nixJNI.new_Dimension__SWIG_0(), true);
  }

  public Dimension(SWIGTYPE_p_std__shared_ptrT_nix__base__IDimension_t p_impl) {
    this(nixJNI.new_Dimension__SWIG_1(SWIGTYPE_p_std__shared_ptrT_nix__base__IDimension_t.getCPtr(p_impl)), true);
  }

  public Dimension(Dimension other) {
    this(nixJNI.new_Dimension__SWIG_3(Dimension.getCPtr(other), other), true);
  }

  public Dimension(SampledDimension other) {
    this(nixJNI.new_Dimension__SWIG_4(SampledDimension.getCPtr(other), other), true);
  }

  public Dimension(RangeDimension other) {
    this(nixJNI.new_Dimension__SWIG_5(RangeDimension.getCPtr(other), other), true);
  }

  public Dimension(SetDimension other) {
    this(nixJNI.new_Dimension__SWIG_6(SetDimension.getCPtr(other), other), true);
  }

  public long index() {
    return nixJNI.Dimension_index(swigCPtr, this);
  }

  public SWIGTYPE_p_DimensionType dimensionType() {
    return new SWIGTYPE_p_DimensionType(nixJNI.Dimension_dimensionType(swigCPtr, this), true);
  }

  public SetDimension asSetDimension() {
    return new SetDimension(nixJNI.Dimension_asSetDimension(swigCPtr, this), true);
  }

  public SampledDimension asSampledDimension() {
    return new SampledDimension(nixJNI.Dimension_asSampledDimension(swigCPtr, this), true);
  }

  public RangeDimension asRangeDimension() {
    return new RangeDimension(nixJNI.Dimension_asRangeDimension(swigCPtr, this), true);
  }

}
