/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class RangeDimension {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RangeDimension(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RangeDimension obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_RangeDimension(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RangeDimension() {
    this(nixJNI.new_RangeDimension__SWIG_0(), true);
  }

  public RangeDimension(RangeDimension other) {
    this(nixJNI.new_RangeDimension__SWIG_1(RangeDimension.getCPtr(other), other), true);
  }

  public long index() {
    return nixJNI.RangeDimension_index(swigCPtr, this);
  }

  public SWIGTYPE_p_DimensionType dimensionType() {
    return new SWIGTYPE_p_DimensionType(nixJNI.RangeDimension_dimensionType(swigCPtr, this), true);
  }

  public SWIGTYPE_p_boost__optionalT_std__string_t label() {
    return new SWIGTYPE_p_boost__optionalT_std__string_t(nixJNI.RangeDimension_label__SWIG_0(swigCPtr, this), true);
  }

  public void label(String label) {
    nixJNI.RangeDimension_label__SWIG_1(swigCPtr, this, label);
  }

  public void label(SWIGTYPE_p_none_t t) {
    nixJNI.RangeDimension_label__SWIG_2(swigCPtr, this, SWIGTYPE_p_none_t.getCPtr(t));
  }

  public SWIGTYPE_p_boost__optionalT_std__string_t unit() {
    return new SWIGTYPE_p_boost__optionalT_std__string_t(nixJNI.RangeDimension_unit__SWIG_0(swigCPtr, this), true);
  }

  public void unit(String unit) {
    nixJNI.RangeDimension_unit__SWIG_1(swigCPtr, this, unit);
  }

  public void unit(SWIGTYPE_p_none_t t) {
    nixJNI.RangeDimension_unit__SWIG_2(swigCPtr, this, SWIGTYPE_p_none_t.getCPtr(t));
  }

  public SWIGTYPE_p_std__vectorT_double_t ticks() {
    return new SWIGTYPE_p_std__vectorT_double_t(nixJNI.RangeDimension_ticks__SWIG_0(swigCPtr, this), true);
  }

  public void ticks(SWIGTYPE_p_std__vectorT_double_t ticks) {
    nixJNI.RangeDimension_ticks__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_double_t.getCPtr(ticks));
  }

  public double tickAt(long index) {
    return nixJNI.RangeDimension_tickAt(swigCPtr, this, index);
  }

  public long indexOf(double position) {
    return nixJNI.RangeDimension_indexOf(swigCPtr, this, position);
  }

  public SWIGTYPE_p_std__vectorT_double_t axis(long count, long startIndex) {
    return new SWIGTYPE_p_std__vectorT_double_t(nixJNI.RangeDimension_axis__SWIG_0(swigCPtr, this, count, startIndex), true);
  }

  public SWIGTYPE_p_std__vectorT_double_t axis(long count) {
    return new SWIGTYPE_p_std__vectorT_double_t(nixJNI.RangeDimension_axis__SWIG_1(swigCPtr, this, count), true);
  }

}
