/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SectionVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SectionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SectionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_SectionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SectionVector() {
    this(nixJNI.new_SectionVector__SWIG_0(), true);
  }

  public SectionVector(long n) {
    this(nixJNI.new_SectionVector__SWIG_1(n), true);
  }

  public long size() {
    return nixJNI.SectionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nixJNI.SectionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nixJNI.SectionVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nixJNI.SectionVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nixJNI.SectionVector_clear(swigCPtr, this);
  }

  public void add(Section x) {
    nixJNI.SectionVector_add(swigCPtr, this, Section.getCPtr(x), x);
  }

  public Section get(int i) {
    return new Section(nixJNI.SectionVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Section val) {
    nixJNI.SectionVector_set(swigCPtr, this, i, Section.getCPtr(val), val);
  }

}
