/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ValueVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ValueVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValueVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nixJNI.delete_ValueVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ValueVector() {
    this(nixJNI.new_ValueVector__SWIG_0(), true);
  }

  public ValueVector(long n) {
    this(nixJNI.new_ValueVector__SWIG_1(n), true);
  }

  public long size() {
    return nixJNI.ValueVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nixJNI.ValueVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nixJNI.ValueVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nixJNI.ValueVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nixJNI.ValueVector_clear(swigCPtr, this);
  }

  public void add(Value x) {
    nixJNI.ValueVector_add(swigCPtr, this, Value.getCPtr(x), x);
  }

  public Value get(int i) {
    return new Value(nixJNI.ValueVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Value val) {
    nixJNI.ValueVector_set(swigCPtr, this, i, Value.getCPtr(val), val);
  }

}
